### ISSUE TITLE
yeah, i got an issue with the commi(fa)sh(ist) weighing one team down to force their undeserved impedance 

### ISSUE THREAD

**Issue by iMightLikeOrange** [jordanmcgowan/softball#5]
`5/20/2019 | 6:30 PM | `**DDSB**` (2nd - 12) v DS (1st - 19) v FCV2 (3rd - 2) | Bryn Mawr #4`

`TUESDAY5/28/2019 | 6:30 PM | DS (2nd - 5) v CA (3rd - 3) v `**DDSB**` (2nd - 5) | Bryn Mawr #4`

`6/3/2019 | 6:30 PM | BNT (2nd - 3) v `**DDSB**` (3rd - 2) v DS (1st - 5) | Bryn Mawr #4 `

`6/10/2019 | 6:30 PM | `**DDSB**` v DS v SFTB | Bryn Mawr #4`

`6/17/2019 | 6:30 PM | FCV2 v CA v `**DDSB**` | Bryn Mawr #4`

`6/24/2019 | 6:30 PM | BNT v `**DDSB**` v FCV2 | Bryn Mawr #4`

`7/1/2019 | 6:30 PM | `**DDSB**` v FCV2 v SFTB | Bryn Mawr #4`

`7/8/2019 | 6:30 PM | BNT v `**DDSB**` v CA | Bryn Mawr #4`

`7/15/2019 | 6:30 PM | CA v SFTB v `**DDSB**` | Bryn Mawr #4`

`7/22/2019 | 6:30 PM | `**DDSB**` v BNT v SFTB | Bryn Mawr #4`

## ***fix***

**Comment by 415DomSmith** [comment]
@jordanmcgowan why do you hate us


or is it fear....?

**Comment by jordanmcgowan** [comment]
#6 handles this - I have tried to update the field positions as best I can: 


|Team|Games on bad field|Games on good field|
|---|---|---|
|DDSB|6|4|
|DS|7|3|
|FCV2|4|6|
|CA|2|8|
|BNT|6|4|
|SFTB|4|6|
